### ISSUE TITLE
`capture_cores=-1,-1` does not create multiple capture threads

### ISSUE THREAD

**Issue by stolyaroleh** [Xilinx-CNS/solarcapture#13]
Section 8.8 of SolarCapture manual contains the following:

• Create 2 capture threads, not affinitized to any particular CPU core:
  `capture_cores=‐1,‐1`

However, [`get_thrd`](https://github.com/Xilinx-CNS/solarcapture/blob/2fd9eb9d3f7a8dd7a0ec37f15f35ad2eca5770ee/src/solar_capture#L987C9-L987C17) function will return the same thread twice [`here`](https://github.com/Xilinx-CNS/solarcapture/blob/2fd9eb9d3f7a8dd7a0ec37f15f35ad2eca5770ee/src/solar_capture#L1002), resulting in two `vi`'s created on the same thread.

Is this expected? Would you accept a PR with a fix, if not?

**Comment by abrunnin-xilinx** [comment]
Absolutely willing to accept a PR.
I do agree it seems that get_thrd only creates a new thread if the name has changed, and the core-id overrides the name.

**Comment by abrunnin-xilinx** [comment]
[13.txt](https://github.com/user-attachments/files/16472476/13.txt)
simplest possible patch to address this.
Though what's people's expectations of specifying capture_cores="2,3,2,5" - do you expect it to act as a set of cores (i.e. use cores 2 3 and 5) or to explicitly specify create a thread on core a, n core b, on core c... ?

**Comment by abrunnin-xilinx** [comment]
I didn't see a PR from you, so implemented this with e185a38be5b0d844f718da7ba5028a8683794934
